version: "3.1"

services:
  db:
    image: mariadb
    ports: ["3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - iepsm_db_management

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - iepsm_db_management

networks:
  iepsm_db_management:
